### ISSUE TITLE
Use blast output as input?

### ISSUE THREAD

**Issue by oushujun** [molbio-dresden/flexidot#5]
Hey, great tool! Looks very promising to combine it with RepeatMasker gff3 annotation, and I love the way of installation - so easy! Every python program should do this!

So I tried it on a 44K-sequence region with heavily nested TE insertions. It runs quite slow on my laptop with 4 threads. Immediately I am thinking: can the program take `BLAST` outputs (i.e., `-outfmt=6`) as inputs, which may be faster for the alignment procedure?

Other thought: I tried it on our CentOs 7 server, the program seems to require a visualization terminal. 
>    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

Can it be run in a server and only generate png/pdf files for laptop visualization?

Thanks again!
Shujun

**Comment by molbio-dresden** [comment]
Hi @oushujun, thank you for your appreciation and your input!

The idea to take `BLAST` results as the basis for a dotplot is a great idea and definitely interesting for us. The output format `-outfmt=6` contains all necessary positional information. So we will give it a try when we work on the next update. You have to keep in mind, that the `BLAST` results give a rougher estimation of shared regions. More importantly, the chosen settings will affect the resulting hit table and thus the downstream dotplot visualization. 

We did not yet approach parallelization of the code as we'd like to stick to the cross platform applicability. Of course, this would speed up FlexiDot. However, we didn't find a suitable Python library for parallelization independent from the operating system. If you have any suggestion, please let us know.

Regarding your issue with the CentOs server installation: We suspect that your error is thrown by the `Matplotlib` module. We observed similar messages during developmental stages which disappeared after updating this module. Maybe it is worth a try to update `Matplotlib` and/or `tkinter`. 

Is it possible for you to specify your last question?

>      Can it be run in a server and only generate png/pdf files for laptop visualization?

Thank you for your feedback and we hope to hear from you. 

Best wishes from Dresden,
Tony & Kathrin

**Comment by molbio-dresden** [comment]
Hello @oushujun,

thanks for the detailed error message. We couldn't reproduce the error on our system. However, we found an entry at stackoverflow, that may help to solve your problem:

[stackoverflow - RuntimeError: Invalid DISPLAY variable](https://stackoverflow.com/questions/35737116/runtimeerror-invalid-display-variable)

It includes two possible solutions:

(1) Declare `import matplotlib` and `matplotlib.use('agg') `before `import pylab as P`. 

(2) Use `P.switch_backend('agg')` after `import pylab as P`.

We attach two FlexiDot versions to this comment, one for each suggested solution. Both versions worked normally on our system.  Another forum post also mentions, that you might need to install PySide. Let us know, if PySide is required in your case and which of the solutions works, if any.

Good luck!
Tony & Kathrin 

[FlexiDot-Issue-Display.zip](https://github.com/molbio-dresden/flexidot/files/2446525/FlexiDot-Issue-Display.zip)

**Comment by oushujun** [comment]
Hi Tony & Kathrin,

Thank you for providing a customized `FlexiDot`. I got a chance to try both solutions in the packet, and they both work!

There is a minor bug complaining not finding the default font:
>/opt/software/miniconda/4.4.10--GCC-4.9.4/envs/flexidot/lib/python2.7/site-packages/matplotlib/font_manager.py:1331: UserWarning: findfont: Font family [u'sans-serif'] not found. Falling back to DejaVu Sans
  (prop.get_family(), self.defaultFamily[fontext]))

That's the thing I can fix on my side. Thanks again!

Best,
Shujun

**Comment by kashiff007** [comment]
Hi @oushujun have able you to use this new FlexiDot script for large genome with blastn table output? If yes, could you please provide the detail of where to use the blast as input?
